# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

output_types <- function() {
    .Call('highlite_output_types', PACKAGE = 'highlite')
}

highlight_ <- function(input, language, output, theme, theme_path, language_path) {
    .Call('highlite_highlight_', PACKAGE = 'highlite', input, language, output, theme, theme_path, language_path)
}

