# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

output_options <- function() {
    .Call('highlite_output_options', PACKAGE = 'highlite')
}

highlight_ <- function(input, type, theme, theme_path, language_path) {
    .Call('highlite_highlight_', PACKAGE = 'highlite', input, type, theme, theme_path, language_path)
}

